# Code

```{r eval=TRUE,echo=TRUE,results='hold'}
# Historical Markers

# https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-07-04

# html output : https://saecanet.com/tidytuesday-2023-07-04-Historical-Markers.html

# Loading packages

# library(tidylog)
library(tidyverse)
rstudioapi::getSourceEditorContext()$path %>% dirname() %>% setwd()

# Loading source data
historical_markers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-07-04/historical_markers.csv')
no_markers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-07-04/no_markers.csv')
```

## Glimpse

```{r eval=TRUE,echo=TRUE,results='hold'}
glimpse(historical_markers)
```

```{r eval=TRUE,echo=TRUE,results='hold'}
glimpse(no_markers)
```

## Check description

```{r eval=TRUE,echo=TRUE,results='hold'}
library(rvest)
(df_description <- 
  'https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-07-04' %>% read_html()  %>% html_table())
```

## Display descriptions

```{r eval=TRUE,echo=TRUE,results='asis'}
df_description[[1]] %>% DT::datatable(options = list(lengthMenu = list(c(10, -1),c("10","All"))))
```

```{r eval=TRUE,echo=TRUE,results='asis'}
df_description[[2]] %>% DT::datatable(options = list(lengthMenu = list(c(10, -1),c("10","All"))))
```

## Check NA

```{r eval=TRUE,echo=TRUE,results='hold'}
historical_markers %>% apply(MARGIN = 2,FUN = function(x)sum(is.na(x))) %>% data.frame()
```

```{r eval=TRUE,echo=TRUE,results='hold'}
no_markers %>% apply(MARGIN = 2,FUN = function(x)sum(is.na(x))) %>% data.frame()
```

## Plot

```{r eval=TRUE,echo=TRUE,results='hold'}
df <- historical_markers
df_hist_by_state <- aggregate(x = df$marker_id,by = list(df$state_or_prov),FUN = length)
colnames(df_hist_by_state)[1] <- 'region'
df_hist_by_state$region <- df_hist_by_state$region %>% tolower()
df_hist_by_state
```

```{r eval=TRUE,echo=TRUE,results='hold'}
MainStates <- map_data("state")
(region <- MainStates$region %>% unique())
```

```{r eval=TRUE,echo=TRUE,results='hold'}
setdiff(df_hist_by_state$region,region)
```

```{r eval=TRUE,echo=TRUE,results='hold'}
setdiff(region,df_hist_by_state$region)
```

```{r eval=TRUE,echo=TRUE,results='hold'}
xrange <- MainStates$long %>% range()
yrange <- MainStates$lat %>% range()
df_number_of_markers_by_state <- plyr::join(x = MainStates,y = df_hist_by_state,by = "region")
l <- (floor(df_number_of_markers_by_state$x/1000)*1000)
e <- l + 999
df_number_of_markers_by_state$Number_of_markers <- paste0(l,' - ',e)
(legendlist <- df_number_of_markers_by_state$Number_of_markers %>% unique())
```

```{r eval=TRUE,echo=TRUE,results='hold'}
df_number_of_markers_by_state$Number_of_markers <- df_number_of_markers_by_state$Number_of_markers %>% factor(levels = legendlist[c(1,3,2,4,5)])
colfunc <- colorRampPalette(c("lightsteelblue","powderblue","blue"))
g1 <- 
  ggplot() + 
  geom_polygon(data = df_number_of_markers_by_state,
               mapping = aes(x = long,y = lat, group=group,fill = Number_of_markers),
               color = "black",
               linewidth = 0.2) +
  scale_fill_manual(values = colfunc(5)) +
  theme_minimal() +
  ylim(yrange) + 
  theme(axis.title = element_blank(),
        axis.text = element_text(size = 15),
        strip.text = element_text(size = 16),
        plot.title = element_text(hjust = 0.5,size = 17),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14)) + 
  labs(title = 'Number of Historical Markers by U.S. state.(U.S. mainland only)') + 
  coord_fixed() + 
  scale_x_continuous(breaks = scales::pretty_breaks(7),limits = xrange)
```

```{r eval=TRUE,echo=TRUE,results='hold'}
AllCounty <- map_data("county")
g0 <- 
  ggplot() + 
  geom_polygon(data = AllCounty,
               mapping = aes(x = long,y = lat,group = group),
               color = "darkblue", 
               fill = "white",
               linewidth = .1 ) +
  geom_polygon(data = MainStates,
               mapping = aes(x = long,y = lat,group = group),
               color = "black",
               fill = "white",
               linewidth = 1,
               alpha = .3) + 
  theme_minimal()
```

```{r eval=TRUE,echo=TRUE,results='hold'}
df_with_year <- df$year_erected %>% {!is.na(.)} %>% df[.,]
df_with_year$Era_of_construction <- (floor(df_with_year$year_erected/50)*50) %>% paste0('-')
```

```{r eval=TRUE,echo=TRUE,results='hold'}
g2 <- 
  g0 + 
  geom_point(mapping = aes(x = longitude_minus_w,y = latitude_minus_s,col = Era_of_construction),
             data = df_with_year,
             size = 2) + 
  ylim(yrange) + 
  theme(axis.title = element_blank(),
        axis.text = element_text(size = 15),
        strip.text = element_text(size = 16),
        plot.title = element_text(hjust = 0.5,size = 17),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14)) + 
  labs(title = 'Location of Historical Marker and date erected.(U.S. mainland only.)\nOnly markers with confirmed year of erection.') + 
  coord_fixed() + 
  scale_x_continuous(breaks = scales::pretty_breaks(7),limits = xrange) +
  scale_color_manual(values = c('red','blue','cyan','orange')) + 
  guides(colour = guide_legend(override.aes = list(size = 5)))
```

```{r eval=TRUE,echo=TRUE,results='hide'}
# Chart output
setwd('D:/tidytuesday/');getwd()
png(paste0("tidytuesday-2023-07-04-Historical-Markers-01.png"),width = 1000,height = 600)
g1 %>% print()
dev.off()
png(paste0("tidytuesday-2023-07-04-Historical-Markers-02.png"),width = 1000,height = 600)
g2 %>% print()
dev.off()

# ALT

## Chart type : The first is the U.S. state coloplus map. The second is a scatter map on a U.S. mainland map.

## Type of data : The first is the number of Historical Markers per U.S. state. The second is the location of the Historical Marker and the date it was erected.

## Reason for including the chart : The first colopress map shows the bias in the number of Historical Markers by state; the second scatter map on the U.S. mainland shows the bias in both specific locations and dates.

## Link to data or source : https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-07-04
```

# `r referencetxt`

- https://en.wikipedia.org/wiki/Historical_Marker_Database
- https://remiller1450.github.io/s230s19/Intro_maps.html
- https://stackoverflow.com/questions/13353213/gradient-of-n-colors-ranging-from-color-1-and-color-2
